import { Manrope } from "next/font/google";
export const manrope = Manrope({ subsets: ["latin"], display: "swap", variable: "--font-manrope" });
export const pestNames: Record<string, string> = {
  Acrobat, Ant: "Acrobat Ant",
  argentineant: "Argentine Ant",
  asianbeetle: "Asian Beetle",
  assassinbug: "Assassin Bug",
  Barn, Spider: "Barn Spider",
  batbug: "Bat Bug",
  bedbug: "Bed Bug",
  blackcricket: "Black Cricket",
  blackwidow: "Black Widow",
  bluemuddauber: "Blue Mud Dauber",
  boxelderbug: "Boxelder Bug",
  brownbandedcockroach: "Brown Banded Cockroach",
  bumblebee: "Bumble Bee",
  carpenterbee: "Carpenter Bee",
  cavecricket: "Cave Cricket",
  cellarspider: "Cellar Spider",
  clovermite: "Clover Mite",
  daddylonglegs: "Daddy Longlegs",
  diggerwasp: "Digger Wasp",
  drugstorebeetle: "Drugstore Beetle",
  europeanhornet: "European Hornet",
  flourbeetle: "Flour Beetle",
  funnelspider: "Funnel Spider",
  gardenspider: "Garden Spider",
  germancockroach: "German Cockroach",
  grainbeetle: "Grain Beetle",
  grassspider: "Grass Spider",
  hobospider: "Hobo Spider",
  honeybee: "Honey Bee",
  jumpingspider: "Jumping Spider",
  indianmealmoth: "Indian Meal Moth",
  housecentipede: "House Centipede",
  ladybug: "Lady Bug",
  japanesebeetle: "Japanese Beetle",
  leafcutterbee: "Leaf Cutter Bee",
  muddauber: "Mud Dauber",
  longjawedspider: "Long Jawed Spider",
  masonbee: "Mason Bee",
  odoroushouseant: "Odorous House Ant",
  orientalcockroach: "Oriental Cockroach",
  paperwasp: "Paper Wasp",
  prayingmantis: "Praying Mantis",
  redwasp: "Red Wasp",
  sawtoothbeetle: "Sawtooth Beetle",
  smokeybrowncockroach: "Smokey Brown Cockroach",
  stinkbug: "Stink Bug",
  subterraneantermite: "Subterranean Termite",
  sweatbee: "Sweat Bee",
  walkingstick: "Walking Stick",
  wolfspider: "Wolf Spider",
  yellowsacspider: "Yellow Sac Spider",
};

