import type { MetadataRoute } from "next";

const baseUrl = "https://allstarpestkc.com";

const routes = [
  "",
  "/about",
  "/services",
  "/cities",
  "/faqs",
  "/contact",
  "/reviews",
  "/blog",
  "/guarantee",
  "/discounts",
  "/text-a-pest-photo",
  "/general-pest-control-kansas-city",
  "/home-pest-control-kansas-city",
  "/commercial-pest-control-kansas-city",
  "/termite-inspection-kansas-city",
  "/termite-treatment-kansas-city",
  "/ants-kansas-city",
  "/spider-control-kansas-city",
  "/rodent-control-kansas-city",
  "/cockroach-exterminator-kansas-city",
  "/bed-bug-treatment-kansas-city",
  "/mosquito-control-kansas-city",
  "/wasp-control-kansas-city",
  "/flea-treatment-kansas-city",
  "/boxelder-bug-control-kansas-city",
  "/stink-bug-control-kansas-city",
  "/silverfish-control-kansas-city",
  "/earwig-control-kansas-city",
  "/centipede-control-kansas-city",
  "/millipede-control-kansas-city",
  "/cricket-control-kansas-city",
  "/tick-control-kansas-city",
  "/beetle-control-kansas-city",
  "/pantry-pest-control-kansas-city",
  "/grain-beetle-control-kansas-city",
  "/moth-control-kansas-city",
  "/carpet-beetle-control-kansas-city",
  "/springtail-control-kansas-city",
  "/clover-mite-control-kansas-city",
  "/sowbug-control-kansas-city",
  "/pillbug-control-kansas-city",
  "/yellowjacket-control-kansas-city",
  "/hornet-control-kansas-city",
  "/paper-wasp-control-kansas-city",
  "/mouse-control-kansas-city",
  "/rat-control-kansas-city",
  "/vole-control-kansas-city",
  "/german-cockroach-control-kansas-city",
  "/american-cockroach-control-kansas-city",
  "/brown-recluse-spider-control-kansas-city",
  "/black-widow-spider-control-kansas-city",
  "/wolf-spider-control-kansas-city",
  "/acrobat-ant-control-kansas-city",
  "/odorous-house-ant-control-kansas-city",
  "/pavement-ant-control-kansas-city",
  "/field-ant-control-kansas-city",
  "/subterranean-termite-control-kansas-city",
  "/termite-prevention-kansas-city",
  "/termite-moisture-control-kansas-city",
  "/crawlspace-termite-inspection-kansas-city",
  "/deck-pest-control-kansas-city",
  "/patio-pest-control-kansas-city",
  "/yard-pest-control-kansas-city",
  "/foundation-pest-control-kansas-city",
  "/attic-pest-control-kansas-city",
  "/kitchen-pest-control-kansas-city",
  "/bathroom-pest-control-kansas-city",
  "/restaurant-pest-control-kansas-city",
  "/office-pest-control-kansas-city",
  "/warehouse-pest-control-kansas-city",
  "/rental-property-pest-control-kansas-city",
  "/landlord-pest-control-kansas-city",
  "/move-in-pest-control-kansas-city",
  "/move-out-pest-control-kansas-city",
];

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((route) => ({
    url: ${baseUrl},
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: route === "" ? 1 : 0.85,
  }));
}
